### ISSUE TITLE
Document certbot URL challenge completion

### ISSUE THREAD

**Issue by stevenstetzler** [dirac-institute/genesis-platform#8]
It looks like certbot needs to complete challenges against the provided URL to ensure that we own it. When I try to use a new URL, `--hub_fqdn=aas.dirac.institute` I get the following:
```
=======
Saving debug log to /Users/steven/Desktop/Projects/genesis-jupyterhub-automator/aas.dirac.institute/secrets/certbot/logs/letsencrypt.log
Plugins selected: Authenticator manual, Installer None
Obtaining a new certificate
Performing the following challenges:
dns-01 challenge for aas.dirac.institute
Running manual-auth-hook command: bin/certbot-auth.sh
manual-auth-hook command "bin/certbot-auth.sh" returned error code 5
Error output from manual-auth-hook command certbot-auth.sh:
jq: error (at <stdin>:1): Cannot index array with string "name"

Waiting for verification...
Challenge failed for domain aas.dirac.institute
dns-01 challenge for aas.dirac.institute
Cleaning up challenges
Some challenges have failed.
IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: aas.dirac.institute
   Type:   dns
   Detail: DNS problem: NXDOMAIN looking up TXT for
   _acme-challenge.aas.dirac.institute
 - Your account credentials have been saved in your Certbot
   configuration directory at
   /Users/steven/Desktop/Projects/genesis-jupyterhub-automator/aas.dirac.institute/secrets/certbot/config.
   You should make a secure backup of this folder now. This
   configuration directory will also contain certificates and private
   keys obtained by Certbot so making regular backups of this folder
   is ideal.
=======
error: something went wrong with SSL certificate generation; see above. aborting..
```
It looks like a TXT record should be added to the managed domain so that this challenge is complete. Do we have documentation or a reference for this @mjuric ?

**Comment by mjuric** [comment]
Here's what I do for Digital Ocean -- there should be a version of this script for Route 53:

https://github.com/genesis-platform/genesis-jupyterhub-automator/blob/master/bin/certbot-auth.sh

and then that should be called from:

https://github.com/genesis-platform/genesis-jupyterhub-automator/blob/master/configure#L187

**Comment by mjuric** [comment]
To be more exact -- the AWS version of the `certbot-auth.sh` script should be passed to `certbot` invocation at:

https://github.com/genesis-platform/genesis-jupyterhub-automator/blob/master/configure#L193

**Comment by mjuric** [comment]
(fwiw, all of this goes away when https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1448 is fixed)

**Comment by stevenstetzler** [comment]
Thanks, this looks like what I need.

**Comment by stevenstetzler** [comment]
I am running into an issue where Certbot doesn't seem to see the changes to the TXT record after they are created in Route53's system. I've created a new `certbot-auth.sh.aws` script in commit 1674819c3489e3beb8e8409f1fc62a9d4372511a that successfully creates a new TXT record for certbot and deletes old TXT records, but it seems the DNS-01 challenge still fails.

If the TXT record is fresh (no previous existing one), I will get:
```
Challenge failed for domain test.dirac.institute
dns-01 challenge for test.dirac.institute
Cleaning up challenges
Some challenges have failed.
IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: test.dirac.institute
   Type:   dns
   Detail: DNS problem: NXDOMAIN looking up TXT for
   _acme-challenge.test.dirac.institute
 - Your account credentials have been saved in your Certbot
   configuration directory at
   /Users/steven/Desktop/Projects/genesis-jupyterhub-automator/test.dirac.institute/secrets/certbot/config.
   You should make a secure backup of this folder now. This
   configuration directory will also contain certificates and private
   keys obtained by Certbot so making regular backups of this folder
   is ideal.
=======
error: something went wrong with SSL certificate generation; see above. aborting..
```
If the TXT file is replaced (I've been running with `aas.dirac.institute` as my hub address for a bit), I will get 
```
Challenge failed for domain aas.dirac.institute
dns-01 challenge for aas.dirac.institute
Cleaning up challenges
Some challenges have failed.
IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: aas.dirac.institute
   Type:   unauthorized
   Detail: Incorrect TXT record
   "<old-txt-value>" found at
   _acme-challenge.aas.dirac.institute

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address.
=======
error: something went wrong with SSL certificate generation; see above. aborting..
```

It looks like there is a delay in the DNS propagation on AWS's end vs what Certbot sees. Was this an issue with Digital Ocean? 

I've tried adding a check at the end of `certbot-auth.sh.aws` that waits for the change becomes available to an AWS cli query, but the change seems to be immediate on our end. I've also tried setting the TXT record TTL to 1 second and waiting up to 10 seconds before letting the `certbot-auth.sh.aws` script to end with no change. The problem seems to be resolved if I wait a full 30 seconds before letting `certbot-auth.sh.aws` end allowing 30 seconds for record changes to propagate, but this adds at least a half-minute delay to the runtime of `configure`. Can you suggest any tweaks or workarounds we could do to resolve this?

**Comment by mjuric** [comment]
Your diagnosis seems plausible -- it Route 53 has some distributed global caching system with eventual consistency, I wouldn't be surprised it took a minute or so for things to fully propagate.

A fixed 1-minute timeout is a good enough solution, I think; one shouldn't be regenerating SSL certs frequently. Just echo a message like "this will take up to a minute..." so the user knows what's going on.

**Comment by mjuric** [comment]
This is being worked on on #9.
